# Generated by Django 3.0.7 on 2020-06-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(help_text='Patient/Contact ID of person 1', max_length=10)),
                ('person2', models.CharField(help_text='Patient/Contact ID of person 2', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(help_text='Patient/Contact ID', max_length=10, primary_key=True, serialize=False)),
                ('tested_positive', models.BooleanField(default=False, help_text='True if person is COVID 19 positive')),
            ],
        ),
    ]
