# Generated by Django 3.0.7 on 2020-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person1', models.CharField(help_text='Patient/Contact ID of person 1', max_length=10)),
                ('person2', models.CharField(help_text='Patient/Contact ID of person 2', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.CharField(help_text='Patient/Contact ID', max_length=10, primary_key=True, serialize=False)),
                ('district', models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTA', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('PKD', 'Palakkad'), ('MLPM', 'Malappuram'), ('KKD', 'Kozhikode'), ('WYD', 'Wayanad'), ('KNR', 'Kannur'), ('KSD', 'Kasaragod'), ('Other State', 'Other State')], max_length=20)),
                ('status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Awaiting result', 'Awaiting result'), ('Not tested', 'Not tested'), ('Recovered', 'Recovered')], default='Not tested', max_length=20)),
            ],
        ),
    ]
