# Generated by Django 3.0.7 on 2020-06-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gen_graph', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='id',
            new_name='p_id',
        ),
    ]
