# Generated by Django 3.0.7 on 2020-06-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gen_graph', '0003_auto_20200607_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(choices=[('TVM', 'Thiruvananthapuram'), ('KLM', 'Kollam'), ('PTA', 'Pathanamthitta'), ('ALP', 'Alappuzha'), ('KTM', 'Kottayam'), ('IDK', 'Idukki'), ('EKM', 'Ernakulam'), ('TSR', 'Thrissur'), ('PKD', 'Palakkad'), ('MLPM', 'Malappuram'), ('KKD', 'Kozhikode'), ('WYD', 'Wayanad'), ('KNR', 'Kannur'), ('KSD', 'Kasaragod'), ('Other State', 'Other State')], default='TVM', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative'), ('Awaiting result', 'Awaiting result'), ('Not tested', 'Not tested')], default='Not tested', max_length=20),
        ),
    ]
